kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: streamline-service
spec:
  ports:
    - port: 80                               # Containers port exposed
      targetPort: 8070                       # Pods port
  selector:
    app: streamlineapp                  # Apply this service to any pods which has the specific label
  type: LoadBalancer                       

